spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://${CODE_ARMOR_DB_HOST}:${CODE_ARMOR_DB_PORT}/codearmor?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${CODE_ARMOR_DB_USERNAME}
    password: ${CODE_ARMOR_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 100

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html

jwt:
  secret: ${CODE_ARMOR_JWT_SECRET}
  expiration: 3600000

app:
  upload:
    dir: ${CODE_ARMOR_UPLOAD_DIR}